Aws crud operations
wal-anudeepthi/fileManagement-BE pull request #6
Opened 2024-09-16 12:32 UTC by wal-vishnuvardhan

File downloading from aws
File deleting from aws
rewriting existing content to aws

2024-09-16 12:33 UTC, Dayana-Wal approved these changes

2024-09-16 12:43 UTC, supriya-wal requested changes

2024-09-16 12:43 UTC, supriya-wal commented on src/files/files.service.ts
> +      if (targettedStorage === 'LocalStorage') {
use switch instead of if

2024-09-16 12:43 UTC, supriya-wal commented on src/files/files.service.ts
> +      } else if (file.targettedStorage === 'Aws') {
try to use capital letters for targettedStorage

2024-09-17 12:37 UTC, supriya-wal approved these changes

2024-09-17 12:37 UTC, merged